@echo off
:: MangaTranslator Launcher - Generated by setup.bat
:: Change to script directory to ensure Python finds all local modules
cd /d "%~dp0"

echo Launching MangaTranslator...
runtime\python.exe app.py %* --open-browser
pause
